nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand.active href="#" CrystalShards.org
  .collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        a.nav-link href="/shards" Shards
      li.nav-item
        a.nav-link href="/popular" Popular
      li.nav-item
        a.nav-link href="/stats" Stats
      li.nav-item
        a.nav-link href="/docs" Docs
      li.nav-item
        a.nav-link href="/contribute" Contribute


